# Generated by Django 4.1.3 on 2022-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rating_merk_id1_alter_rating_merk_id2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='merk_id1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='merk_id2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='merk_id3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='merk_id4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='merk_id5',
            field=models.IntegerField(default=0),
        ),
    ]
